In [1]:
import pandas as pd
df = pd.read_csv("120-years-of-olympic-history-athletes-and-results.csv")

print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Rows: 271116, Columns: 15

In [6]:
df = pd.read_csv("120-years-of-olympic-history-athletes-and-results.csv")

french_headers = ['ID', 'Nom', 'Sexe', 'Âge', 'Taille', 'Poids', 'Équipe', 'NOC', 'Jeux', 'Année', 'Saison', 'Ville', 'Sport', 'Événement', 'Médaille']
df.columns = french_headers

df.head()

,ID,Nom,Sexe,Âge,Taille,Poids,Équipe,NOC,Jeux,Année,Saison,Ville,Sport,Événement,Médaille
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [7]:
df = pd.read_csv("120-years-of-olympic-history-athletes-and-results.csv", index_col=0)

df.head()

,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
ID,,,,,,,,,,,,,,
1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [8]:
df_by_position = df.iloc[:, [0, 3, 4]]
df_by_position.head()

                        Name  Height  Weight
ID
1                  A Dijiang   180.0    80.0
2                   A Lamusi   170.0    60.0
3        Gunnar Nielsen Aaby     NaN     NaN
4       Edgar Lindenau Aabye     NaN     NaN
5   Christine Jacoba Aaftink   185.0    82.0

In [9]:
df_by_name = df[['Name', 'Height', 'Weight']]
df_by_name.head()

                        Name  Height  Weight
ID
1                  A Dijiang   180.0    80.0
2                   A Lamusi   170.0    60.0
3        Gunnar Nielsen Aaby     NaN     NaN
4       Edgar Lindenau Aabye     NaN     NaN
5   Christine Jacoba Aaftink   185.0    82.0

In [10]:
print(df.dtypes)

Name          str
Sex           str
Age       float64
Height    float64
Weight    float64
Team          str
NOC           str
Games         str
Year        int64
Season        str
City          str
Sport         str
Event         str
Medal         str
dtype: object

In [11]:
df['Year'] = pd.to_datetime(df['Year'], format='%Y')

print(df['Year'].dtypes)

datetime64[us]

In [15]:
!pip install openpyxl

import pandas as pd
excel_data = pd.read_excel("120-years-of-olympic-history-athletes-and-results.xlsx")
excel_data.head()

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [19]:
import sqlite3

connection = sqlite3.connect('chinook.db')
sql_data = pd.read_sql("SELECT * FROM sqlite_master", connection)
sql_data.head()

,type,name,tbl_name,rootpage,sql
0,table,albums,albums,2,"CREATE TABLE ""albums""\r\n(\r\n [AlbumId] IN..."
1,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,artists,artists,4,"CREATE TABLE ""artists""\r\n(\r\n [ArtistId] ..."
3,table,customers,customers,5,"CREATE TABLE ""customers""\r\n(\r\n [Customer..."
4,table,employees,employees,8,"CREATE TABLE ""employees""\r\n(\r\n [Employee..."

In [21]:
json_data = pd.read_json("employees.json")
json_data.head()

,EmployeeId,LastName,FirstName,Title,ReportsTo,BirthDate,HireDate,Address,City,State,Country,PostalCode,Phone,Fax,Email
0,1,Adams,Andrew,General Manager,NaN,1962-02-18 00:00:00,2002-08-14 00:00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,1958-12-08 00:00:00,2002-05-01 00:00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,1973-08-29 00:00:00,2002-04-01 00:00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,1947-09-19 00:00:00,2003-05-03 00:00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,1965-03-03 00:00:00,2003-10-17 00:00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [24]:
weight_series = pd.read_csv(
    "120-years-of-olympic-history-athletes-and-results.csv", 
    usecols=[1, 5],     
    index_col=0,         
).squeeze("columns")     

print(type(weight_series))
print(weight_series.head())

<class 'pandas.Series'>
Name
A Dijiang                   80.0
A Lamusi                    60.0
Gunnar Nielsen Aaby          NaN
Edgar Lindenau Aabye         NaN
Christine Jacoba Aaftink    82.0
Name: Weight, dtype: float64

In [25]:
aalto_w = weight_series.loc["Antti Sami Aalto"]
ya_w = weight_series.loc["Andrzej ya"]

print(f"Antti Sami Aalto: {aalto_w}")
print(f"Andrzej ya: {ya_w}")

Antti Sami Aalto: 96.0
Andrzej ya: 89.0

In [27]:
manual_series = pd.Series(["B", "D", "C", "A"], index=[1, 3, 2, 0])
print(manual_series)

1    B
3    D
2    C
0    A
dtype: str

In [28]:
over_90 = df[df['Weight'] > 90]
print(f"Found {len(over_90)} athletes over 90kg.")

Found 16819 athletes over 90kg.

In [29]:
between_90_100 = df[(df['Weight'] > 90) & (df['Weight'] < 100)]
print(f"Found {len(between_90_100)} athletes in the 90-100kg range.")

Found 9892 athletes in the 90-100kg range.

In [32]:
weight_series_view = df['Weight'].loc[1000:271115]
weight_series_view

ID
1000      100.0
1001       55.0
1002       69.0
1003       56.0
1003       56.0
          ...
135569     89.0
135570     59.0
135570     59.0
135571     96.0
135571     96.0
Name: Weight, Length: 269309, dtype: float64

In [36]:
df['Weight'].reset_index(drop=True).head(20)

0     80.0
1     60.0
2      NaN
3      NaN
4     82.0
5     82.0
6     82.0
7     82.0
8     82.0
9     82.0
10    75.0
11    75.0
12    75.0
13    75.0
14    75.0
15    75.0
16    75.0
17    75.0
18    72.0
19    72.0
Name: Weight, dtype: float64

In [37]:
print(f"Size of the weight series: {df['Weight'].size}")

Size of the weight series: 271116

In [38]:
df['Weight'].describe()

count    208241.000000
mean         70.702393
std          14.348020
min          25.000000
25%          60.000000
50%          70.000000
75%          79.000000
max         214.000000
Name: Weight, dtype: float64

In [48]:
exact_name = df[df['Name'].str.contains(r'^Usain\b', regex=True)]['Name'].unique()[0]

df_names = df.set_index("Name") 
bolt_data = df_names.loc[exact_name] 
bolt_data

,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
Name,,,,,,,,,,,,,
Usain St. Leo Bolt,M,17.0,196.0,95.0,Jamaica,JAM,2004 Summer,2004-01-01,Summer,Athina,Athletics,Athletics Men's 200 metres,NaN
Usain St. Leo Bolt,M,21.0,196.0,95.0,Jamaica,JAM,2008 Summer,2008-01-01,Summer,Beijing,Athletics,Athletics Men's 100 metres,Gold
Usain St. Leo Bolt,M,21.0,196.0,95.0,Jamaica,JAM,2008 Summer,2008-01-01,Summer,Beijing,Athletics,Athletics Men's 200 metres,Gold
Usain St. Leo Bolt,M,21.0,196.0,95.0,Jamaica,JAM,2008 Summer,2008-01-01,Summer,Beijing,Athletics,Athletics Men's 4 x 100 metres Relay,NaN
Usain St. Leo Bolt,M,25.0,196.0,95.0,Jamaica,JAM,2012 Summer,2012-01-01,Summer,London,Athletics,Athletics Men's 100 metres,Gold
Usain St. Leo Bolt,M,25.0,196.0,95.0,Jamaica,JAM,2012 Summer,2012-01-01,Summer,London,Athletics,Athletics Men's 200 metres,Gold
Usain St. Leo Bolt,M,25.0,196.0,95.0,Jamaica,JAM,2012 Summer,2012-01-01,Summer,London,Athletics,Athletics Men's 4 x 100 metres Relay,Gold
Usain St. Leo Bolt,M,29.0,196.0,95.0,Jamaica,JAM,2016 Summer,2016-01-01,Summer,Rio de Janeiro,Athletics,Athletics Men's 100 metres,Gold
Usain St. Leo Bolt,M,29.0,196.0,95.0,Jamaica,JAM,2016 Summer,2016-01-01,Summer,Rio de Janeiro,Athletics,Athletics Men's 200 metres,Gold
Usain St. Leo Bolt,M,29.0,196.0,95.0,Jamaica,JAM,2016 Summer,2016-01-01,Summer,Rio de Janeiro,Athletics,Athletics Men's 4 x 100 metres Relay,Gold

In [50]:
cols_to_compare = ["Year", "Event", "Medal"]
comparison = df_names.loc[["Usain St. Leo Bolt", "Justin Alexander Gatlin"], cols_to_compare]

comparison.sort_values(by="Year")

,Year,Event,Medal
Name,,,
Usain St. Leo Bolt,2004-01-01,Athletics Men's 200 metres,NaN
Justin Alexander Gatlin,2004-01-01,Athletics Men's 100 metres,Gold
Justin Alexander Gatlin,2004-01-01,Athletics Men's 200 metres,Bronze
Justin Alexander Gatlin,2004-01-01,Athletics Men's 4 x 100 metres Relay,Silver
Usain St. Leo Bolt,2008-01-01,Athletics Men's 100 metres,Gold
Usain St. Leo Bolt,2008-01-01,Athletics Men's 200 metres,Gold
Usain St. Leo Bolt,2008-01-01,Athletics Men's 4 x 100 metres Relay,NaN
Usain St. Leo Bolt,2012-01-01,Athletics Men's 100 metres,Gold
Usain St. Leo Bolt,2012-01-01,Athletics Men's 200 metres,Gold
Usain St. Leo Bolt,2012-01-01,Athletics Men's 4 x 100 metres Relay,Gold
Justin Alexander Gatlin,2012-01-01,Athletics Men's 4 x 100 metres Relay,NaN
Justin Alexander Gatlin,2012-01-01,Athletics Men's 100 metres,Bronze
Justin Alexander Gatlin,2016-01-01,Athletics Men's 100 metres,Silver
Usain St. Leo Bolt,2016-01-01,Athletics Men's 200 metres,Gold
Justin Alexander Gatlin,2016-01-01,Athletics Men's 200 metres,NaN
Usain St. Leo Bolt,2016-01-01,Athletics Men's 100 metres,Gold
Usain St. Leo Bolt,2016-01-01,Athletics Men's 4 x 100 metres Relay,Gold
Justin Alexander Gatlin,2016-01-01,Athletics Men's 4 x 100 metres Relay,NaN

In [51]:
female_gold = df[(df['Sex'] == 'F') & (df['Medal'] == 'Gold')]
female_gold.head()

,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
ID,,,,,,,,,,,,,,
21,Ragnhild Margrethe Aamodt,F,27.0,163.0,NaN,Norway,NOR,2008 Summer,2008-01-01,Summer,Beijing,Handball,Handball Women's Handball,Gold
150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900 Summer,1900-01-01,Summer,Paris,Golf,Golf Women's Individual,Gold
832,Nicola Virginia Adams,F,29.0,164.0,51.0,Great Britain,GBR,2012 Summer,2012-01-01,Summer,London,Boxing,Boxing Women's Flyweight,Gold
832,Nicola Virginia Adams,F,33.0,164.0,51.0,Great Britain,GBR,2016 Summer,2016-01-01,Summer,Rio de Janeiro,Boxing,Boxing Women's Flyweight,Gold
846,Valerie Kasanita Adams-Vili (-Price),F,23.0,193.0,120.0,New Zealand,NZL,2008 Summer,2008-01-01,Summer,Beijing,Athletics,Athletics Women's Shot Put,Gold

In [52]:
df.isnull().sum()

Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [53]:
df_cleaned_height = df.dropna(subset=['Height'])

In [54]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Height'] = df['Height'].fillna(df['Height'].mean())
df['Weight'] = df['Weight'].fillna(df['Weight'].mean())

In [68]:
duplicates_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates_count}")
#ran it twice so result shows 0

Number of duplicate rows: 0

In [66]:
df_no_duplicates = df.drop_duplicates()

lines_left = len(df_no_duplicates)
print(f"Number of lines left after deleting duplicates: {lines_left}")

Number of lines left after deleting duplicates: 269731

In [60]:
print(f"The shape of the dataframe is: {df_no_duplicates.shape}")

The shape of the dataframe is: (269731, 14)

In [63]:
sport_stats = df.groupby("Sport").mean(numeric_only=True).loc[:, ['Age', 'Height', 'Weight']]

sport_stats

                        Age      Height     Weight
Sport
Aeronautics       26.000000  175.338970  70.702393
Alpine Skiing     23.226236  173.999252  71.684645
Alpinism          34.040483  175.338970  70.702393
Archery           27.853707  173.559066  70.143818
Art Competitions  41.501821  175.324897  70.762779
...                     ...         ...        ...
Tug-Of-War        28.338256  176.389121  78.322837
Volleyball        25.184786  186.580498  78.594361
Water Polo        25.654285  182.222473  80.521863
Weightlifting     25.504882  169.597893  78.453549
Wrestling         25.781722  173.111806  74.256741

[66 rows x 3 columns]

In [64]:
multi_stats = df.groupby(["Sport", "Sex"])[['Age', 'Height', 'Weight']].mean()

multi_stats

                         Age      Height     Weight
Sport         Sex
Aeronautics   M    26.000000  175.338970  70.702393
Alpine Skiing F    22.334609  169.036674  64.521777
              M    23.784098  177.104175  76.166219
Alpinism      F    43.000000  175.338970  70.702393
              M    33.667170  175.338970  70.702393
...                      ...         ...        ...
Water Polo    M    25.725843  183.190182  82.024742
Weightlifting F    24.028078  160.563751  67.724622
              M    25.701704  170.801925  79.883454
Wrestling     F    25.305921  163.865132  60.587837
              M    25.802838  173.522169  74.863361

[116 rows x 3 columns]